/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LiquidBtn: typeof import('./components/LiquidGlass/LiquidBtn/LiquidBtn.vue')['default']
    LiquidBtnToggle: typeof import('./components/LiquidGlass/LiquidBtnToggle/LiquidBtnToggle.vue')['default']
    LiquidContainer: typeof import('./components/LiquidGlass/LiquidContainer/LiquidContainer.vue')['default']
    LiquidProgress: typeof import('./components/LiquidGlass/LiquidProgress/LiquidProgress.vue')['default']
    LiquidSearchBar: typeof import('./components/LiquidGlass/LiquidSearchBar/LiquidSearchBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
