/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LiquidBtn: typeof import('./components/LiquidGlass/LiquidBtn/LiquidBtn.vue')['default']
    LiquidBtnToggle: typeof import('./components/LiquidGlass/LiquidBtnToggle/LiquidBtnToggle.vue')['default']
    LiquidChip: typeof import('./components/LiquidGlass/LiquidChip/LiquidChip.vue')['default']
    LiquidContainer: typeof import('./components/LiquidGlass/LiquidContainer/LiquidContainer.vue')['default']
    LiquidDivider: typeof import('./components/LiquidGlass/LiquidDivider/LiquidDivider.vue')['default']
    LiquidIcon: typeof import('./components/LiquidGlass/LiquidIcon/LiquidIcon.vue')['default']
    LiquidProgress: typeof import('./components/LiquidGlass/LiquidProgress/LiquidProgress.vue')['default']
    LiquidProgressCircular: typeof import('./components/LiquidGlass/LiquidProgressCircular/LiquidProgressCircular.vue')['default']
    LiquidSearchBar: typeof import('./components/LiquidGlass/LiquidSearchBar/LiquidSearchBar.vue')['default']
    LiquidSwitch: typeof import('./components/LiquidGlass/LiquidSwitch/LiquidSwitch.vue')['default']
    LiquidTextField: typeof import('./components/LiquidGlass/LiquidTextField/LiquidTextField.vue')['default']
    LiquidTimerRing: typeof import('./components/LiquidGlass/LiquidTimerRing/LiquidTimerRing.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
